permalink:           pretty
title:               Y8 2017 spring in shibuya
url:                 http://y8-2017-spring.hachiojipm.org/
paginate:            1
baseurl:             ""
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle


sass:
  sass_dir:          _sass
  style:            :compressed

gems:
  - jekyll-paginate
  - jekyll-gist
